spring.application.name=airline_tickets
spring.datasource.url=jdbc:mysql://localhost:3306/airline_tickets?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=locvip92
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rkorkey@gmail.com
spring.mail.password=ovuq vkzi mzud luec
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
