spring.application.name=airline_tickets
spring.datasource.url=jdbc:mysql://localhost:3306/module5_case_study?createDatabaseIfNotExist=true
spring.datasource.username=
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
